int i = 0 ;
int distance = 0 ;
void Mesure();
int ardublockUltrasonicSensorCodeAutoGeneratedReturnCM(int trigPin, int echoPin)
{
  long duration;
  pinMode(trigPin, OUTPUT);
  pinMode(echoPin, INPUT);
  digitalWrite(trigPin, LOW);
  delayMicroseconds(2);
  digitalWrite(trigPin, HIGH);
  delayMicroseconds(20);
  digitalWrite(trigPin, LOW);
  duration = pulseIn(echoPin, HIGH);
  duration = duration / 59;
  if ((duration < 2) || (duration > 300)) return false;
  return duration;
}

void Stop();
void Demitour();
void Tournergauche();
void Tournerdroite();
void Reculer();
void Incrementation();
void Avancer();

void setup()
{
  digitalWrite( 10 , LOW );

  pinMode( 7 , OUTPUT);
  pinMode( 6 , OUTPUT);
  pinMode( 5 , OUTPUT);
  pinMode( 4 , OUTPUT);
  pinMode( 2 , OUTPUT);
  pinMode( 3 , OUTPUT);
  i = 0 ;

}

void loop()
{
  delay( 3000 );
  while ( ( ( i ) < ( 9 ) ) )
  {
    Mesure();
    if (( ( i ) == ( 0 ) ))
    {
      Avancer();
      Incrementation();
      Mesure();
    }
    if (( ( ( distance ) < ( 8 ) ) && ( ( ( i ) == ( 2 ) ) || ( ( ( i ) == ( 3 ) ) || ( ( i ) == ( 7 ) ) ) ) ))
    {
      Tournergauche();
      Mesure();
    }
    if (( ( ( distance ) < ( 8 ) ) && ( ( ( i ) == ( 1 ) ) || ( ( i ) == ( 4 ) ) ) ))
    {
      Tournerdroite();
      Mesure();
    }
    if (( ( ( distance ) < ( 8 ) ) && ( ( i ) == ( 6 ) ) ))
    {
      Demitour();
      Mesure();
    }
    if (( ( ( distance ) < ( 8 ) ) && ( ( i ) == ( 5 ) ) ))
    {
      Reculer();
      Mesure();
    }
    Avancer();
    if (( ( ( distance ) < ( 8 ) ) && ( ( i ) == ( 8 ) ) ))
    {
      Stop();
      Incrementation();
    }
  }

}

void Mesure()
{
  delay( 100 );
  distance = 	ardublockUltrasonicSensorCodeAutoGeneratedReturnCM( 10 , 11 ) ;
}

void Stop()
{
  digitalWrite(7 , LOW);
  digitalWrite(6 , LOW);
  analogWrite(5 , 255);
  digitalWrite(4 , LOW);
  digitalWrite(2 , LOW);
  analogWrite(3 , 255);
  delay( 1000 );
  Incrementation();
}

void Demitour()
{
  digitalWrite(7 , HIGH);
  digitalWrite(6 , LOW);
  analogWrite(5 , 255);
  digitalWrite(4 , LOW);
  digitalWrite(2 , HIGH);
  analogWrite(3 , 255);
  delay( 1100 );
  Incrementation();
}

void Tournergauche()
{
  digitalWrite(7 , HIGH);
  digitalWrite(6 , LOW);
  analogWrite(5 , 255);
  digitalWrite(4 , LOW);
  digitalWrite(2 , HIGH);
  analogWrite(3 , 255);
  delay( 550 );
  Incrementation();
}

void Tournerdroite()
{
  digitalWrite(7 , LOW);
  digitalWrite(6 , HIGH);
  analogWrite(5 , 255);
  digitalWrite(4 , HIGH);
  digitalWrite(2 , LOW);
  analogWrite(3 , 255);
  delay( 550 );
  Incrementation();
}

void Reculer()
{
  digitalWrite(7 , LOW);
  digitalWrite(6 , HIGH);
  analogWrite(5 , 255);
  digitalWrite(4 , LOW);
  digitalWrite(2 , HIGH);
  analogWrite(3 , 255);
  delay( 1000 );
  Incrementation();
}

void Incrementation()
{
  i = ( i + 1 ) ;
}

void Avancer()
{
  digitalWrite(7 , HIGH);
  digitalWrite(6 , LOW);
  analogWrite(5 , 255);
  digitalWrite(4 , HIGH);
  digitalWrite(2 , LOW);
  analogWrite(3 , 255);
}


